constants =
  "E_ERROR":
    value: 1,
    description: "Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.",
    note: ""

  "E_WARNING":
    value: 2,
    description: "Run-time warnings (non-fatal errors). Execution of the script is not halted.",
    note: ""

  "E_PARSE":
    value: 4,
    description: "Compile-time parse errors. Parse errors should only be generated by the parser.",
    note: ""

  "E_NOTICE":
    value: 8,
    description: "Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.",
    note: ""

  "E_CORE_ERROR":
    value: 16,
    description: "Fatal errors that occur during PHP's initial startup. This is like an E_ERROR, except it is generated by the core of PHP.",
    note: ""

  "E_CORE_WARNING":
    value: 32,
    description: "Warnings (non-fatal errors) that occur during PHP's initial startup. This is like an E_WARNING, except it is generated by the core of PHP.",
    note: ""

  "E_COMPILE_ERROR":
    value: 64,
    description: "Fatal compile-time errors. This is like an E_ERROR, except it is generated by the Zend Scripting Engine.",
    note: ""

  "E_COMPILE_WARNING":
    value: 128,
    description: "Compile-time warnings (non-fatal errors). This is like an E_WARNING, except it is generated by the Zend Scripting Engine.",
    note: ""

  "E_USER_ERROR":
    value: 256,
    description: "User-generated error message. This is like an E_ERROR, except it is generated in PHP code by using the PHP function trigger_error().",
    note: ""

  "E_USER_WARNING":
    value: 512,
    description: "User-generated warning message. This is like an E_WARNING, except it is generated in PHP code by using the PHP function trigger_error().",
    note: ""

  "E_USER_NOTICE":
    value: 1024,
    description: "User-generated notice message. This is like an E_NOTICE, except it is generated in PHP code by using the PHP function trigger_error().",
    note: ""

module.exports =
  constants: constants
  max: 2047
  eAllValue: 2047
