module.exports =
  "E_ERROR":
    description: "Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.",
    note: ""

  "E_WARNING":
    description: "Run-time warnings (non-fatal errors). Execution of the script is not halted.",
    note: ""

  "E_PARSE":
    description: "Compile-time parse errors. Parse errors should only be generated by the parser.",
    note: ""

  "E_NOTICE":
    description: "Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.",
    note: ""

  "E_CORE_ERROR":
    description: "Fatal errors that occur during PHP's initial startup. This is like an E_ERROR, except it is generated by the core of PHP.",
    note: ""

  "E_CORE_WARNING":
    description: "Warnings (non-fatal errors) that occur during PHP's initial startup. This is like an E_WARNING, except it is generated by the core of PHP.",
    note: ""

  "E_COMPILE_ERROR":
    description: "Fatal compile-time errors. This is like an E_ERROR, except it is generated by the Zend Scripting Engine.",
    note: ""

  "E_COMPILE_WARNING":
    description: "Compile-time warnings (non-fatal errors). This is like an E_WARNING, except it is generated by the Zend Scripting Engine.",
    note: ""

  "E_USER_ERROR":
    description: "User-generated error message. This is like an E_ERROR, except it is generated in PHP code by using the PHP function trigger_error().",
    note: ""

  "E_USER_WARNING":
    description: "User-generated warning message. This is like an E_WARNING, except it is generated in PHP code by using the PHP function trigger_error().",
    note: ""

  "E_USER_NOTICE":
    description: "User-generated notice message. This is like an E_NOTICE, except it is generated in PHP code by using the PHP function trigger_error().",
    note: ""

  "E_STRICT":
    description: "Enable to have PHP suggest changes to your code which will ensure the best interoperability and forward compatibility of your code.",
    note: "Since PHP 5 but not included in E_ALL until PHP 5.4.0"

  "E_RECOVERABLE_ERROR":
    description: "Catchable fatal error. It indicates that a probably dangerous error occurred, but did not leave the Engine in an unstable state. If the error is not caught by a user defined handle (see also set_error_handler()), the application aborts as it was an E_ERROR.",
    note: "Since PHP 5.2.0"

  "E_DEPRECATED":
    description: "Run-time notices. Enable this to receive warnings about code that will not work in future versions.",
    note: "Since PHP 5.3.0"

  "E_USER_DEPRECATED":
    description: "User-generated warning message. This is like an E_DEPRECATED, except it is generated in PHP code by using the PHP function trigger_error().",
    note: "Since PHP 5.3.0"
